require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7.0
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/factories/**/*'
    - 'bin/**/*'
    - 'lib/tasks/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Style/Encoding:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
